name: Publish Pull Requests
on: [push, pull_request]

jobs:
  pr-package:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/setup-node/issues/1222
      # once resolved, replace with `- run: corepack enable`
      - name: Force Install Corepack and Enable
        run: npm install -g corepack && corepack enable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Publish preview package
        run: pnpx pkg-pr-new publish --no-template